apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  selector:
    app: items
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer